### PR TITLE
feature/move-files-styling

### LINKED ISSUE #315: Move File Modal UX updates
This issue is a list of UX changes to the Move Files Modal:

- [x] Remove check mark from confirm button
- [x] Add Cancel Button 
- [x] Sentence casing for menu item 'Move Files'
- [x] No tool tip on confirm
- [x] Change wording from "Move" to "Copy"
- [x] Change wording on NAS Cache, (VAST)
- [ ] Set column width of move files manifest
- [x] Column ellipsis with file extension
- [x] Selected file count in bottom right of table
- [x] Default table styling 
- [ ] Make scrollbar disappear when not scrolling.
- [x]  ? Split table into 2 sections 
- [x]  ? Log how long files will be available

### PR DESCRIPTION
**Pull request by BrianWhitneyAI**
The purpose of this PR is to resolve #315 and clean up the "Copy files" modal. This PR only resolves some of the items as UX changes related to to some of the requests are dependent on future ETL work.

### CODE REVIEW

**Comment by BrianWhitneyAI** [comment]
Screenshot 2024-12-18 at 12 24 12 PM

**Comment by pgarrison** [comment]
I suggest not using "Cache" or "lease". Perhaps the following instead:

Copy Files to Local NAS (Vast)

Files copied to the local NAS (Vast) are stored with a 180-day expiration, after which they revert to cloud-only. To extend the expiration, simply reselect the files and confirm the update.

Files that are already on Vast: Extend expiration

Files to download to Vast

**Comment by BrianWhitneyAI** [comment]
> a94c95e

resolved in [a94c95e](https://github.com/AllenInstitute/biofile-finder/pull/320/commits/a94c95ec654332708ddf91c18015248ce4ad3f80)

**Comment by BrianWhitneyAI** [comment]
> I suggest not using "Cache" or "lease": I think these terms will be unfamiliar in this context. Perhaps the following instead:
> 
> Copy Files to Local NAS (Vast)
> 
> Files copied to the local NAS (Vast) are stored with a 180-day expiration, after which they revert to cloud-only. To extend the expiration, simply reselect the files and confirm the update.
> 
> Files that are already on Vast: Extend expiration
> 
> Files to download to Vast

resolved in [a94c95e](https://github.com/AllenInstitute/biofile-finder/pull/320/commits/a94c95ec654332708ddf91c18015248ce4ad3f80)

**Review by SeanLeRoy — APPROVED** [review]
LGTM assuming we add the total file size count to the bottom of both tables as discussed in slack

**Comment by lynwilhelm** [comment]
Thanks for requesting my eyes @pgarrison. Your suggestions were right on and Brian and I chatted on a couple additional minor edits that are now resolved.

**Comment by BrianWhitneyAI** [comment]
## Here are some screenshots!

Screenshot 2024-12-19 at 3 38 32 PM

Screenshot 2024-12-19 at 3 53 00 PM

**Comment by saeliddp** [comment]
Nit: the expiration/eviction period is currently 182 days, not 180. We can change this on the backend if desired. Could also say '6 months' on the frontend, or maybe it's not an important distinction to the users 🤷 . Just wanted to let you know if you were unaware

Also, glad to see all of my integration test files are being used for something else 😆

**Review by kmitcham — APPROVED** [review]
Glad to see us using the word 'vast' instead of cache in much of the UI, as I think that is more clear to our users.

**Comment by BrianWhitneyAI** [comment]
> Nit: the expiration/eviction period is currently 182 days, not 180. We can change this on the backend if desired. Could also say '6 months' on the frontend, or maybe it's not an important distinction to the users 🤷 . Just wanted to let you know if you were unaware
> 
> Also, glad to see all of my integration test files are being used for something else 😆

Those tests have been so helpful! The original text said ~180 days, knowing it was 182. I think its ok to tell users 180 here, Im also ok with 6 months

**Comment by BrianWhitneyAI** [comment]
> Glad to see us using the word 'vast' instead of cache in much of the UI, as I think that is more clear to our users.

Yeah I'm still unsure about "NAS" and if users will know what that is but Vast is now alot clearer.

**Comment by pgarrison** [comment]
> Yeah I'm still unsure about "NAS" and if users will know what that is but Vast is now alot clearer.

I think leaving out "local NAS" entirely makes sense. I don't think our users really know what it means either.

**Review by SeanLeRoy — APPROVED** [review]

**Pull request merged**
